application:
  version: 0.0.1
  title: Projeto base para estudos
spring:
  datasource:
    url: jdbc:mysql://${MYSQL_HOST}:${MYSQL_PORT}/actionsandkubernetes
    username: ${MYSQL_USER}
    password: ${MYSQL_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
  flyway:
    enabled: true
    locations: classpath:db.migration
    baseline-on-migrate: true
    validate-on-migrate: true
    databaseType: mysql
  springdoc:
    writer-with-order-by-keys: true
    swagger-ui:
      path: /documentacao.html
      operationsSorter: method
      tagsSorter: alpha
    api-docs:
      path: /documentacao
server:
  port: 8080
  servlet:
    context-path: /api